# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-29 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20170529_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
