# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-05 00:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20170529_2010'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('sorted', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='carrots',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
