# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-05 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_auto_20170605_0010'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
