# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-05 18:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20170605_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='carrots',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
